### ISSUE TITLE
[Feature] Add support for the Shadowsocks 2022-blake3-chacha8-poly1305 cipher

### ISSUE THREAD

**Issue by passingwang** [MetaCubeX/mihomo#1396]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

Now mihomo doesn't support the `2022-blake3-chacha8-poly1305` cipher. It has been implemented by [shadowsocks-rust](github.com/shadowsocks/shadowsocks-rust).

### Possible Solution

 I think replacing the last argument of the function [XORKeyStream](https://github.com/aead/chacha20/blob/master/chacha/chacha.go#L140) with 8 can easily implement it.

**Comment by wwqgtxx** [comment]
fixed in https://github.com/MetaCubeX/mihomo/commit/345061a7cc1d533048e1519b2a71742a55dca31c

**Comment by Restia-Ashbell** [comment]
@wwqgtxx 
There seems to be an issue. When using `2022-blake3-chacha8-poly1305` method in Shadowsocks, the mihomo client fails to connect to a shadowsocks-rust server, and the server log shows:
```
WARN tokio-runtime-worker ThreadId(03) shadowsocks_service::server::tcprelay: tcp handshake failed. peer: [::ffff:127.0.0.1]:61019, decrypt header chunk failed
```
I corrected the constructor in this [PR](https://github.com/MetaCubeX/sing-shadowsocks2/pull/2), but the error still persists.

@passingwang 
Have you tested the connection between mihomo and shadowsocks-rust?

**Comment by Skyxim** [comment]
@Restia-Ashbell Please submit PR upstream
https://github.com/SagerNet/sing-shadowsocks2

**Comment by Restia-Ashbell** [comment]
> I corrected the constructor in this [PR](https://github.com/MetaCubeX/sing-shadowsocks2/pull/2), but the error still persists.

https://github.com/MetaCubeX/chacha/commit/b3f4a9aea21617efd128f5cb0e148c7283fe5877
I've found the reason — it was already fixed recently, but I haven't updated the dependency yet.
